server:
  address: ${INFRA_BIND_ADDRESS:0.0.0.0}
  port: 8888

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: config-server
  cloud:
    config: 
      server: 
        git: 
          uri: https://github.com/PhuNguyen12345/mss301-digital-library-microservices.git
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: ${CONFIG_BRANCH:main}
          search-paths: infra/config-repo

eureka:
  instance:
    hostname: ${INTERNAL_SERVICE_HOST:localhost}
    prefer-ip-address: false
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
