spring.application.name=identity-service

identity.keycloak.base-url=${KEYCLOAK_BASE_URL:http://localhost:8080}
identity.keycloak.realm=${KEYCLOAK_REALM:digilib}
identity.keycloak.client-id=${KEYCLOAK_CLIENT_ID:identity-service}
identity.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:}
identity.keycloak.default-enabled=${KEYCLOAK_DEFAULT_ENABLED:true}
