spring:
  application:
    name: identity-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/digilib_identity}
    username: ${SPRING_DATASOURCE_USERNAME:simpi}
    password: ${SPRING_DATASOURCE_PASSWORD:1231}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

identity:
  keycloak:
    base-url: ${KEYCLOAK_BASE_URL:http://localhost:8080}
    realm: ${KEYCLOAK_REALM:digilib}
    client-id: ${KEYCLOAK_CLIENT_ID:identity-service}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:}
    default-enabled: ${KEYCLOAK_DEFAULT_ENABLED:true}