CREATE TABLE fine_policy (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_rate BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    lost_threshold_days INTEGER NOT NULL,
    lost_penalty BIGINT NOT NULL,
    create_at TIMESTAMP NOT NULL,
    update_at TIMESTAMP,

    CONSTRAINT ck_fine_policy_daily_rate CHECK (daily_rate >= 0),
    CONSTRAINT ck_fine_policy_lost_threshold_days CHECK (lost_threshold_days > 0),
    CONSTRAINT ck_fine_policy_lost_penalty CHECK (lost_penalty >= 0)
);

CREATE TABLE fines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id INTEGER NOT NULL,
    loan_id BIGINT NOT NULL,
    book_id BIGINT,
    student_id VARCHAR(100) NOT NULL,
    student_email VARCHAR(100),
    reason VARCHAR(30) NOT NULL,
    due_date TIMESTAMP NOT NULL,
    return_date TIMESTAMP,
    amount_due BIGINT NOT NULL,
    compensation_amount BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(50) NOT NULL,
    waiver_reason VARCHAR(255),
    paid_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    create_at TIMESTAMP NOT NULL,
    update_at TIMESTAMP NOT NULL,

    CONSTRAINT uk_fines_loan_id UNIQUE (loan_id),
    CONSTRAINT fk_fines_policy
        FOREIGN KEY (policy_id)
            REFERENCES fine_policy (id),
    CONSTRAINT ck_fines_reason
        CHECK (reason IN ('OVERDUE_RETURN', 'OVERDUE_THRESHOLD', 'LOST_BOOK')),
    CONSTRAINT ck_fines_status
        CHECK (status IN ('PENDING', 'PAID', 'WAIVED')),
    CONSTRAINT ck_fines_amount_due CHECK (amount_due >= 0),
    CONSTRAINT ck_fines_compensation_amount CHECK (compensation_amount >= 0),
    CONSTRAINT ck_fines_return_date CHECK (return_date IS NULL OR return_date >= due_date)
);

CREATE TABLE payment_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fine_id INTEGER NOT NULL,
    payment_code VARCHAR(50) NOT NULL,
    amount BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    provider VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    sepay_transaction_id VARCHAR(100),
    sepay_reference_code VARCHAR(100),
    paid_at TIMESTAMP,
    expires_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT uk_payment_attempts_payment_code UNIQUE (payment_code),
    CONSTRAINT uk_payment_attempts_sepay_transaction_id UNIQUE (sepay_transaction_id),
    CONSTRAINT uk_payment_attempts_sepay_reference_code UNIQUE (sepay_reference_code),
    CONSTRAINT fk_payment_attempts_fine
        FOREIGN KEY (fine_id)
            REFERENCES fines (id)
            ON DELETE CASCADE,
    CONSTRAINT ck_payment_attempts_provider
        CHECK (provider IN ('SEPAY')),
    CONSTRAINT ck_payment_attempts_status
        CHECK (status IN ('CREATED', 'PENDING', 'SUCCEEDED', 'FAILED', 'EXPIRED', 'CANCELLED', 'REFUNDED')),
    CONSTRAINT ck_payment_attempts_amount CHECK (amount >= 0)
);

CREATE INDEX idx_fines_student_status ON fines (student_id, status);
CREATE INDEX idx_fines_policy_id ON fines (policy_id);
CREATE INDEX idx_payment_attempts_fine_status ON payment_attempts (fine_id, status);
