CREATE TABLE categories (
                            category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            category_name VARCHAR(100) NOT NULL,
                            description TEXT NOT NULL,
                            is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE classifications (
                                 classification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 classification_system VARCHAR(50) NOT NULL,
                                 classification_name VARCHAR(100) NOT NULL,
                                 classification_code INTEGER NOT NULL,
                                 is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE books (
                       book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       isbn VARCHAR(20) UNIQUE,
                       title VARCHAR(255) NOT NULL,
                       author VARCHAR(150) NOT NULL,
                       publisher VARCHAR(150) NOT NULL,
                       publication_year INTEGER NOT NULL,
                       edition VARCHAR(50) NOT NULL,

    -- Trạng thái quản lý đầu sách
                       book_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

                       created_at TIMESTAMP,
                       updated_at TIMESTAMP,
                       language VARCHAR(50) NOT NULL,
                       description VARCHAR(500) NOT NULL,
                       cover_image_url VARCHAR(255),

                       category_id BIGINT NOT NULL,
                       classification_id BIGINT NOT NULL,
                       is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

                       CONSTRAINT fk_books_category
                           FOREIGN KEY (category_id)
                               REFERENCES categories (category_id),

                       CONSTRAINT fk_books_classification
                           FOREIGN KEY (classification_id)
                               REFERENCES classifications (classification_id)
);

CREATE TABLE book_copies (
                             copy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             barcode VARCHAR(50) NOT NULL UNIQUE,
                             shelf_location VARCHAR(50) NOT NULL,
                             acquisition_date DATE NOT NULL,

    -- Trạng thái của từng bản sách vật lý
                             copy_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',

                             book_id BIGINT NOT NULL,
                             is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

                             CONSTRAINT fk_book_copies_book
                                 FOREIGN KEY (book_id)
                                     REFERENCES books (book_id)
);

CREATE TABLE digital_resources (
                                   resource_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   file_format VARCHAR(20) NOT NULL,
                                   resource_url VARCHAR(255) NOT NULL,
                                   access_permission VARCHAR(20) NOT NULL,
                                   uploaded_at TIMESTAMP,
                                   book_id BIGINT NOT NULL,
                                   is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

                                   CONSTRAINT fk_digital_resources_book
                                       FOREIGN KEY (book_id)
                                           REFERENCES books (book_id)
);

CREATE TABLE book_audit_logs (
                                 log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 action VARCHAR(20) NOT NULL,
                                 user_id BIGINT NOT NULL,
                                 changed_at TIMESTAMP NOT NULL,
                                 book_id BIGINT NOT NULL,

                                 CONSTRAINT fk_book_audit_logs_book
                                     FOREIGN KEY (book_id)
                                         REFERENCES books (book_id)
);

CREATE INDEX idx_books_category_id ON books (category_id);
CREATE INDEX idx_books_classification_id ON books (classification_id);
CREATE INDEX idx_books_book_status ON books (book_status);
CREATE INDEX idx_book_copies_book_id ON book_copies (book_id);
CREATE INDEX idx_book_copies_copy_status ON book_copies (copy_status);
CREATE INDEX idx_digital_resources_book_id ON digital_resources (book_id);
CREATE INDEX idx_book_audit_logs_book_id ON book_audit_logs (book_id);