spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      mvc:
        routes:
          - id: catalog-service
            uri: lb://catalog-service
            predicates:
              - Path=/api/catalog/**
              - Header=X-Client-Type,web

          - id: loan-service
            uri: lb://loan-service
            predicates:
              - Path=/api/loan/**
              - Header=X-Client-Type,web
