CREATE TABLE notification_policy (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type       VARCHAR(255) NOT NULL,
    subject_template VARCHAR(255) NOT NULL,
    body_template    VARCHAR(255) NOT NULL,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    create_at        TIMESTAMP    NOT NULL,
    update_at        TIMESTAMP
);

CREATE TABLE notification_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id    BIGINT        NOT NULL,
    student_id     VARCHAR(255)  NOT NULL,
    student_email  VARCHAR(255),
    channel        VARCHAR(50)   NOT NULL,
    status         VARCHAR(50)   NOT NULL,
    sent_at        TIMESTAMP,
    read_at        TIMESTAMP,
    failure_reason VARCHAR(500),
    create_at      TIMESTAMP     NOT NULL,
    update_at      TIMESTAMP,

    CONSTRAINT fk_notification_log_template
        FOREIGN KEY (template_id) REFERENCES notification_policy (id),
    CONSTRAINT ck_notification_log_channel
        CHECK (channel IN ('EMAIL', 'WEBSITE')),
    CONSTRAINT ck_notification_log_status
        CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'UNREAD', 'READ'))
);

CREATE INDEX idx_notification_log_student_id ON notification_log (student_id);
CREATE INDEX idx_notification_log_student_channel ON notification_log (student_id, channel);
CREATE INDEX idx_notification_log_status ON notification_log (status);
CREATE INDEX idx_notification_log_create_at ON notification_log (create_at);
CREATE INDEX idx_notification_policy_event_type ON notification_policy (event_type);
