spring:
  application:
    name: member-service

  # Reactive Database Setup via R2DBC
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/digilib_member
    username: simpi
    password: 1231
  # Flyway Migration Setup (operates via JDBC)
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/digilib_member
    user: simpi
    password: "1231"
    locations: classpath:db/migration
    baseline-on-migrate: true

  # Security Decoding Parameters pointing to your Keycloak Setup
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.huynq.space/realms/digilib-realm
          jwk-set-uri: https://keycloak.huynq.space/realms/digilib-realm/protocol/openid-connect/certs


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

keycloak:
  base-url: https://keycloak.huynq.space
  realm: digilib-realm
  client-id: digilib-auth
  client-secret: MtmhLbjfzrt1vmEbzbEZGQ4vZitsRaqj
  config:
    import: "optional:configserver:http://localhost:8888"
