CREATE TABLE loans (
    loan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id VARCHAR(255) NOT NULL,
    book_id BIGINT NOT NULL,
    copy_id BIGINT,
    book_type VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL,
    borrowed_at TIMESTAMP NOT NULL,
    due_date TIMESTAMP NOT NULL,
    returned_at TIMESTAMP,
    renewal_count INTEGER NOT NULL,
    max_renewals INTEGER NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_loans_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_loans_book_type CHECK (book_type IN ('PHYSICAL', 'DIGITAL')),
    CONSTRAINT ck_loans_status CHECK (status IN ('BORROWED', 'RETURNED', 'OVERDUE', 'LOST')),
    CONSTRAINT ck_loans_renewal_count CHECK (renewal_count >= 0),
    CONSTRAINT ck_loans_max_renewals CHECK (max_renewals >= 0),
    CONSTRAINT ck_loans_due_date CHECK (due_date >= borrowed_at),
    CONSTRAINT ck_loans_physical_copy CHECK (book_type <> 'PHYSICAL' OR copy_id IS NOT NULL)
);

CREATE TABLE loan_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id BIGINT,
    from_status VARCHAR(30),
    to_status VARCHAR(30) NOT NULL,
    changed_by VARCHAR(255) NOT NULL,
    reason VARCHAR(255) NOT NULL,
    changed_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_loan_status_history_loan
        FOREIGN KEY (loan_id)
            REFERENCES loans (loan_id)
            ON DELETE CASCADE,
    CONSTRAINT ck_loan_history_from_status
        CHECK (from_status IS NULL OR from_status IN ('BORROWED', 'RETURNED', 'OVERDUE', 'LOST')),
    CONSTRAINT ck_loan_history_to_status
        CHECK (to_status IN ('BORROWED', 'RETURNED', 'OVERDUE', 'LOST'))
);

CREATE TABLE saga_outbox (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id BIGINT NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(255) NOT NULL,
    retry_count INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    processed_at TIMESTAMP,

    CONSTRAINT fk_saga_outbox_loan
        FOREIGN KEY (loan_id)
            REFERENCES loans (loan_id)
            ON DELETE CASCADE,
    CONSTRAINT ck_saga_outbox_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED')),
    CONSTRAINT ck_saga_outbox_retry_count CHECK (retry_count >= 0)
);

CREATE TABLE saga_log (
    saga_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id BIGINT NOT NULL,
    saga_type VARCHAR(255) NOT NULL,
    current_step VARCHAR(255) NOT NULL,
    overall_status VARCHAR(255) NOT NULL,
    compensations INTEGER NOT NULL,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,

    CONSTRAINT fk_saga_log_loan
        FOREIGN KEY (loan_id)
            REFERENCES loans (loan_id)
            ON DELETE CASCADE,
    CONSTRAINT ck_saga_log_type
        CHECK (saga_type IN ('BORROW_BOOK', 'RETURN_BOOK', 'RENEW_BOOK', 'RESERVE_BOOK')),
    CONSTRAINT ck_saga_log_compensations CHECK (compensations >= 0)
);

CREATE TABLE reservations (
    reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    queue_position INTEGER NOT NULL,
    reserved_at TIMESTAMP NOT NULL,
    notified_at TIMESTAMP,
    expires_at TIMESTAMP,

    CONSTRAINT ck_reservations_status
        CHECK (status IN ('WAITING', 'NOTIFIED', 'EXPIRED', 'COMPLETED')),
    CONSTRAINT ck_reservations_queue_position CHECK (queue_position > 0),
    CONSTRAINT ck_reservations_expiry CHECK (expires_at IS NULL OR expires_at >= reserved_at)
);

CREATE INDEX idx_loans_member_id ON loans (member_id);
CREATE INDEX idx_loans_book_id ON loans (book_id);
CREATE INDEX idx_loans_copy_id ON loans (copy_id);
CREATE INDEX idx_loans_status ON loans (status);
CREATE INDEX idx_loans_due_date ON loans (due_date);
CREATE INDEX idx_loans_member_status ON loans (member_id, status);
CREATE INDEX idx_loan_status_history_loan_id ON loan_status_history (loan_id);
CREATE INDEX idx_saga_outbox_status_created_at ON saga_outbox (status, created_at);
CREATE INDEX idx_saga_outbox_loan_id ON saga_outbox (loan_id);
CREATE INDEX idx_saga_log_loan_id ON saga_log (loan_id);
CREATE INDEX idx_reservations_member_id ON reservations (member_id);
CREATE INDEX idx_reservations_book_id ON reservations (book_id);
CREATE INDEX idx_reservations_book_status ON reservations (book_id, status);
