CREATE TABLE borrow_requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id VARCHAR(255) NOT NULL,
    book_id BIGINT NOT NULL,
    book_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    loan_id BIGINT,
    requested_at TIMESTAMP NOT NULL,
    processed_at TIMESTAMP,
    processed_by VARCHAR(255),
    rejection_reason VARCHAR(500),
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_borrow_requests_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT uk_borrow_requests_loan_id UNIQUE (loan_id),
    CONSTRAINT fk_borrow_requests_loan
        FOREIGN KEY (loan_id)
            REFERENCES loans (loan_id),
    CONSTRAINT ck_borrow_requests_book_type
        CHECK (book_type IN ('PHYSICAL', 'DIGITAL')),
    CONSTRAINT ck_borrow_requests_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT ck_borrow_requests_processing
        CHECK (
            (status = 'PENDING' AND processed_at IS NULL)
            OR (status <> 'PENDING' AND processed_at IS NOT NULL)
        ),
    CONSTRAINT ck_borrow_requests_approval
        CHECK (
            (status = 'APPROVED' AND loan_id IS NOT NULL)
            OR (status <> 'APPROVED' AND loan_id IS NULL)
        )
);

CREATE INDEX idx_borrow_requests_member_requested_at
    ON borrow_requests (member_id, requested_at DESC);

CREATE INDEX idx_borrow_requests_status_requested_at
    ON borrow_requests (status, requested_at DESC);

CREATE UNIQUE INDEX ux_borrow_requests_pending_member_book
    ON borrow_requests (member_id, book_id)
    WHERE status = 'PENDING';
