server:
  address: ${INTERNAL_SERVICE_BIND_ADDRESS:127.0.0.1}
  port: ${NOTIFICATION_SERVICE_PORT:8085}

spring:
  application:
    name: notification-service
  config:
    import:
      - "optional:file:.env[.properties]"
      - "${CONFIG_SERVER_IMPORT:optional:configserver:http://localhost:8888}"
