server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/catalog/**
            - Header=X-Client-Type,web
          filters:
            # 1. Cấu hình Retry
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, INTERNAL_SERVER_ERROR
                methods: GET
                backoff:
                  firstBackoff: 500ms
                  maxBackoff: 2000ms
                  factor: 2
                  basedOnPreviousValue: false
            # 2. Cấu hình Circuit Breaker & Fallback
            - name: CircuitBreaker
              args:
                name: catalogCircuitBreaker
                fallbackUri: forward:/fallback/catalog

        - id: loan-service
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/api/loan/**
            - Header=X-Client-Type,web

        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/members/**
            - Header=X-Client-Type,web
  
management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        includes:
          - health
          - info
          - gateway
          - metrics
          - circuitbreakers

# Cấu hình ngưỡng của Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      catalogCircuitBreaker:
        registerHealthIndicator: true # Ép hiển thị số liệu của circuit breaker ở endpoint /actuator/health
        slidingWindowSize: 5          # Dựa trên 5 request gần nhất
        failureRateThreshold: 50      # Nếu > 50% request lỗi -> OPEN
        waitDurationInOpenState: 5s  # Đợi 5s trong trạng thái OPEN trước khi sang HALF_OPEN
        permittedNumberOfCallsInHalfOpenState: 3 # giới hạn số lần gọi khi ở trạng thái HALF_OPEN
        automaticTransitionFromOpenToHalfOpenEnabled: true # Bật tự động chuyển mạch sau khi hết thời gian chờ
  timelimiter:
    instances:
      catalogCircuitBreaker:
        timeoutDuration: 2s           # Timeout 2 giây cho Kịch bản 2

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
