server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: catalog-service
            uri: lb://catalog-service
            predicates:
              - Path=/api/catalog/**
              - Header=X-Client-Type,web


          - id: loan-service
            uri: lb://loan-service
            predicates:
              - Path=/api/loan/**
              - Header=X-Client-Type,web
  
management:
  endpoints:
    web:
      exposure:
        includes:
          - health
          - info
          - gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
