server:
  address: ${INTERNAL_SERVICE_BIND_ADDRESS:0.0.0.0}
  port: 8081

spring:
  application:
    name: catalog-service
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  datasource:
    url: jdbc:postgresql://${CATALOG_DB_HOST:localhost}:${CATALOG_DB_PORT:5432}/${CATALOG_DB_NAME:catalog_service_dbs}
    username: ${CATALOG_DB_USERNAME:postgres}
    password: ${CATALOG_DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    hostname: ${INTERNAL_SERVICE_HOST:catalog-service}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka/}
