server:
  port: 8082

spring:
  application:
    name: catalog-service
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:catalog_service_dbs}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  bulkhead:
    instances:
      catalogBulkhead:
        maxConcurrentCalls: 1
        maxWaitDuration: 0 # Không chờ đợi, đầy là ném ngoại lệ (fallback) luôn
