name: CD - Catalog Service

on:
  push:
    tags:
      - "catalog-service/*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  catalog-service:
    uses: ./.github/workflows/_service-cd.yml
    with:
      module: services/catalog-service
      service_name: catalog-service
      host_port: "8081"
      container_port: "8081"
    secrets: inherit
