name: CD - Config Server

on:
  push:
    tags:
      - "config-server/*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  config-server:
    uses: ./.github/workflows/_service-cd.yml
    with:
      module: infra/config-server
      service_name: config-server
      host_port: "8888"
      container_port: "8888"
    secrets: inherit
