name: CD - Fine Service

on:
  push:
    tags:
      - "fine-service/*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fine-service:
    uses: ./.github/workflows/_service-cd.yml
    with:
      module: services/fine-service
      service_name: fine-service
      host_port: "8084"
      container_port: "8084"
    secrets: inherit
