name: CD - Loan Service

on:
  push:
    tags:
      - "loan-service/*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  loan-service:
    uses: ./.github/workflows/_service-cd.yml
    with:
      module: services/loan-service
      service_name: loan-service
      host_port: "8083"
      container_port: "8083"
    secrets: inherit
