name: CD - Notification Service

on:
  push:
    tags:
      - "notification-service/*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  notification-service:
    uses: ./.github/workflows/_service-cd.yml
    with:
      module: services/notification-service
      service_name: notification-service
      host_port: "8085"
      container_port: "8085"
    secrets: inherit
