name: CI - Config Server

on:
  push:
    branches:
      - main
    paths:
      - infra/config-server/**
      - pom.xml
      - Dockerfile
      - .dockerignore
      - .github/workflows/_service-ci.yml
      - .github/workflows/_service-cd.yml
      - .github/workflows/cicd-config-server.yml
  pull_request:
    paths:
      - infra/config-server/**
      - pom.xml
      - Dockerfile
      - .dockerignore
      - .github/workflows/_service-ci.yml
      - .github/workflows/cicd-config-server.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  config-server-ci:
    uses: ./.github/workflows/_service-ci.yml
    with:
      module: infra/config-server
      image_name: config-server
      ignore_test_failures: true
    secrets: inherit

  config-server-cd:
    needs: config-server-ci
    if: github.event_name == 'push'
    uses: ./.github/workflows/_service-cd.yml
    with:
      service_name: config-server
      host_port: "8888"
      container_port: "8888"
    secrets: inherit
